# Generated by Django 2.2.6 on 2020-03-20 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='author_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TestModel.User'),
        ),
    ]
