# Generated by Django 2.2.6 on 2020-03-20 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20200320_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author_id',
            new_name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
