# Generated by Django 2.2.6 on 2020-03-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_auto_20200320_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
