# Generated by Django 2.2.6 on 2020-03-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0008_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TestModel.User')),
            ],
        ),
    ]
